---
features:
  - |
    This changes network config generation with ansible, using the provided
    jinja templates for roles, the default. Too keep using old heat templates
    for network config with``OS::TripleO::{{role.name}}::Net::SoftwareConfig``
    mappings, use ``NetworkConfigWithAnsible: false`` ``parameter_default``
    in an environment file. 
deprecations:
  - |
    The old way of generating network configs with heat templates has been
    deprecated.
