heat_template_version: rocky

description: >
  External Swift Proxy endpoint configured with Puppet

parameters:
  ServiceData:
    default: {}
    description: Dictionary packing service data
    type: json
  ServiceNetMap:
    default: {}
    description: Mapping of service_name -> network name. Typically set
                 via parameter_defaults in the resource registry.  This
                 mapping overrides those in ServiceNetMapDefaults.
    type: json
  DefaultPasswords:
    default: {}
    type: json
  RoleName:
    default: ''
    description: Role name on which the service is applied
    type: string
  RoleParameters:
    default: {}
    description: Parameters specific to the role
    type: json
  EndpointMap:
    default: {}
    description: Mapping of service endpoint -> protocol. Typically set
                 via parameter_defaults in the resource registry.
    type: json
  ExternalPublicUrl:
    description: (DEPRECATED) Public endpoint url for the external swift proxy
    type: string
    default: 'deprecated'
  ExternalInternalUrl:
    description: (DEPRECATED) Internal endpoint url for the external swift proxy
    type: string
    default: 'deprecated'
  ExternalAdminUrl:
    description: (DEPRECATED) External endpoint url for the external swift proxy
    type: string
    default: 'deprecated'
  ExternalSwiftPublicUrl:
    description: Public endpoint url for the external swift proxy
    type: string
  ExternalSwiftInternalUrl:
    description: Internal endpoint url for the external swift proxy
    type: string
  ExternalSwiftAdminUrl:
    description: External endpoint url for the external swift proxy
    type: string
  ExternalSwiftUserTenant:
    description: Tenant where swift user will be set as admin
    type: string
    default: 'service'
  SwiftPassword:
    description: The password for the swift service account
    type: string
    hidden: true
  KeystoneRegion:
    type: string
    default: 'regionOne'
    description: Keystone region for endpoint

parameter_groups:
- label: deprecated
  description: |
   The following parameters are deprecated and will be removed. They should not
   be relied on for new deployments. If you have concerns regarding deprecated
   parameters, please contact the TripleO development team on IRC or the
   OpenStack mailing list.
  parameters:
  - ExternalAdminUrl
  - ExternalInternalUrl
  - ExternalPublicUrl

resources:

conditions:
  deprecated_external_admin_url: {not: {equals: [{get_param: ExternalAdminUrl}, 'deprecated']}}
  deprecated_external_internal_url: {not: {equals: [{get_param: ExternalInternalUrl}, 'deprecated']}}
  deprecated_external_public_url: {not: {equals: [{get_param: ExternalPublicUrl}, 'deprecated']}}

outputs:
  role_data:
    description: Role data for External Swift proxy.
    value:
      service_name: external_swift_proxy
      config_settings:

      step_config:

      service_config_settings:
        keystone:
          swift::keystone::auth::public_url:
            if:
            - deprecated_external_public_url
            - {get_param: ExternalPublicUrl}
            - {get_param: ExternalSwiftPublicUrl}
          swift::keystone::auth::internal_url:
            if:
            - deprecated_external_internal_url
            - {get_param: ExternalInternalUrl}
            - {get_param: ExternalSwiftInternalUrl}
          swift::keystone::auth::admin_url:
            if:
            - deprecated_external_admin_url
            - {get_param: ExternalAdminUrl}
            - {get_param: ExternalSwiftAdminUrl}
          swift::keystone::auth::public_url_s3: ''
          swift::keystone::auth::internal_url_s3: ''
          swift::keystone::auth::admin_url_s3: ''
          swift::keystone::auth::password: {get_param: SwiftPassword}
          swift::keystone::auth::region: {get_param: KeystoneRegion}
          swift::keystone::auth::tenant: {get_param: ExternalSwiftUserTenant}
          swift::keystone::auth::configure_s3_endpoint: false
          swift::keystone::auth::operator_roles:
            - admin
            - swiftoperator
            - ResellerAdmin

