parameter_defaults:
  ControllerNetworkConfigTemplate: 'templates/ci/multiple_nics_ipv6.j2'
  ControllerNetworkConfigWithAnsible: true
  ComputeNetworkConfigTemplate: 'templates/ci/multiple_nics_ipv6.j2'
  ComputeNetworkConfigWithAnsible: true
  BlockStorageNetworkConfigTemplate: 'templates/ci/multiple_nics_ipv6.j2'
  BlockStorageNetworkConfigWithAnsible: true
  CellControllerNetworkConfigTemplate: 'templates/ci/multiple_nics_ipv6.j2'
  CellControllerNetworkConfigWithAnsible: true
  ObjectStorageNetworkConfigTemplate: 'templates/ci/multiple_nics_ipv6.j2'
  ObjectStorageNetworkConfigWithAnsible: true
  CephStorageNetworkConfigTemplate: 'templates/ci/multiple_nics_ipv6.j2'
  CephStorageNetworkConfigWithAnsible: true
  ExternalNetCidr: 2001:db8:fd00:1000::/64
  ExternalAllocationPools: [{"start": "2001:db8:fd00:1000::10", "end": "2001:db8:fd00:1000:ffff:ffff:ffff:fffe"}]
  ExternalInterfaceDefaultRoute: 2001:db8:fd00:1000::1
  InternalApiNetCidr: fd00:fd00:fd00:2000::/64
  InternalApiAllocationPools: [{"start": "fd00:fd00:fd00:2000::10", "end": "fd00:fd00:fd00:2000:ffff:ffff:ffff:fffe"}]
  StorageNetCidr: fd00:fd00:fd00:3000::/64
  StorageAllocationPools: [{"start": "fd00:fd00:fd00:3000::10", "end": "fd00:fd00:fd00:3000:ffff:ffff:ffff:fffe"}]
  StorageMgmtNetCidr: fd00:fd00:fd00:4000::/64
  StorageMgmtAllocationPools: [{"start": "fd00:fd00:fd00:4000::10", "end": "fd00:fd00:fd00:4000:ffff:ffff:ffff:fffe"}]
  TenantNetCidr: 172.16.0.0/24
  TenantAllocationPools: [{"start": "172.16.0.10", "end": "172.16.0.250"}]
