heat_template_version: rocky

description: >
  HAproxy service configured with Puppet

parameters:
  ServiceData:
    default: {}
    description: Dictionary packing service data
    type: json
  ServiceNetMap:
    default: {}
    description: Mapping of service_name -> network name. Typically set
                 via parameter_defaults in the resource registry.  This
                 mapping overrides those in ServiceNetMapDefaults.
    type: json
  DefaultPasswords:
    default: {}
    type: json
  RoleName:
    default: ''
    description: Role name on which the service is applied
    type: string
  RoleParameters:
    default: {}
    description: Parameters specific to the role
    type: json
  EndpointMap:
    default: {}
    description: Mapping of service endpoint -> protocol. Typically set
                 via parameter_defaults in the resource registry.
    type: json
  CAMap:
    description: >
      Map containing the CA certs and information needed for deploying them.
    default: {}
    type: json

outputs:
  role_data:
    description: Role data for injecting CA certificates.
    value:
      service_name: ca_certs
      config_settings:
        description: Extra hieradata needed to inject CA certificates
        value: null
  host_prep_tasks:
    description: Extra ansible tasks needed to inject CA certificates
    value:
      - name: inject CA certs into the system store
        import_role:
          name: tripleo_update_trusted_cas
        vars:
          tripleo_update_trusted_cas_ca_map: {get_param: CAMap}

