parameter_defaults:
  ControllerNetworkConfigTemplate: 'templates/ci/multiple_nics.j2'
  ControllerNetworkConfigWithAnsible: true
  ComputeNetworkConfigTemplate: 'templates/ci/multiple_nics.j2'
  ComputeNetworkConfigWithAnsible: true
  BlockStorageNetworkConfigTemplate: 'templates/ci/multiple_nics.j2'
  BlockStorageNetworkConfigWithAnsible: true
  CellControllerNetworkConfigTemplate: 'templates/ci/multiple_nics.j2'
  CellControllerNetworkConfigWithAnsible: true
  ObjectStorageNetworkConfigTemplate: 'templates/ci/multiple_nics.j2'
  ObjectStorageNetworkConfigWithAnsible: true
  CephStorageNetworkConfigTemplate: 'templates/ci/multiple_nics.j2'
  CephStorageNetworkConfigWithAnsible: true
  ExternalNetCidr: 10.0.0.0/24
  ExternalAllocationPools: [{"start": "10.0.0.10", "end": "10.0.0.50"}]
  ExternalInterfaceDefaultRoute: 10.0.0.1
  PublicVirtualFixedIPs: [{ "ip_address": "10.0.0.5" }]
  InternalApiNetCidr: 172.17.0.0/24
  InternalApiAllocationPools: [{"start": "172.17.0.10", "end": "172.17.0.250"}]
  StorageNetCidr: 172.18.0.0/24
  StorageAllocationPools: [{"start": "172.18.0.10", "end": "172.18.0.250"}]
  StorageMgmtNetCidr: 172.19.0.0/24
  StorageMgmtAllocationPools: [{"start": "172.19.0.10", "end": "172.19.0.250"}]
  TenantNetCidr: 172.16.0.0/24
  TenantAllocationPools: [{"start": "172.16.0.10", "end": "172.16.0.250"}]
